model: ECAPATDNN
trainfunc: aamsoftmax
save_path: exps/ECAPATDNN_AAM_1
batch_size: 400
eval_frames: 400
max_frames: 200
lr_decay: 0.97
weight_decay: 5e-05
max_seg_per_spk: 500
augment: True
nOut: 192
lr: 0.001
margin: 0.2
scale: 30
